TebLocalPlannerROS:
 odom_topic: odom
 map_frame: map
 
 # Trajectory
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: true
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5
 
 # Robot
 max_vel_x: 0.5
 max_vel_x_backwards: 0.2
 max_vel_theta: 1.0
 acc_lim_x: 0.35
 acc_lim_theta: 0.6
 min_turning_radius: 0.0
 
 footprint_model:
  type: circular
  radius: 0.4
  
 # GoalTolerance
 xy_goal_tolerance: 0.5
 yaw_goal_tolerance: 3.14
 free_goal_vel: false
 
 # Obstacles
 min_obstacle_dist: 0.08
 include_costmap_obstacles: true
 costmap_obstacles_behind_robot_dist: 0.1
 obstacles_poses_affected: 30.0
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: true
 costmap_converter_rate: 10.0

 
