map_type: costmap
obstacle_range: 5.6
raytrace_range: 5.6
max_obstacle_height: 2
min_obstacle_height: 0.0

# Cost Params
inflation_radius: 0.3
costscalingfactor: 5

global_frame: map
robot_base_frame: base_link
always_send_full_costmap: false

observation_sources: scan
scan: {sensor_frame: base_laser_1, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
